import PropTypes from "prop-types";
import React from "react";
import BuildingBlocks from "./images/BuildingBlocks.svg";
import Button from "./images/Button.svg";
import styles from 'index.module.css'
import Image from "next/image";

export const ModalDatePicker = ({
  headlineRange = "Aug 17 – Aug 23",
  supportingTextRange = "Depart - Return dates",
}) => {
  return (
    <div className="modal-date-picker">
      <div className="header">
        <div className="frame">
          <div className="container-wrapper">
            <Image className="img" alt="Container" src="container.svg" />
          </div>
          <Button
            className="button-instance"
            labelText="Save"
            labelTextClassName="design-component-instance-node"
            showIcon={false}
            style="text"
          />
        </div>
        <div className="labe-date-icon">
          <div className="label-date">
            <div className="section-header">{supportingTextRange}</div>
            <p className="selected-date">{headlineRange}</p>
          </div>
          <div className="container-wrapper">
            <Image className="img" alt="Container" src="image.svg" />
          </div>
        </div>
      </div>
      <div className="days-of-the-week">
        <div className="date-wrapper-2">
          <div className="date-2">S</div>
        </div>
        <div className="date-wrapper-2">
          <div className="date-2">M</div>
        </div>
        <div className="date-wrapper-2">
          <div className="date-2">T</div>
        </div>
        <div className="date-wrapper-2">
          <div className="date-2">W</div>
        </div>
        <div className="date-wrapper-2">
          <div className="date-2">T</div>
        </div>
        <div className="date-wrapper-2">
          <div className="date-2">F</div>
        </div>
        <div className="date-wrapper-2">
          <div className="date-2">S</div>
        </div>
      </div>
      <div className="months">
        <div className="month-group">
          <div className="month">
            <div className="month-year-wrapper">
              <div className="month-year">August 2023</div>
            </div>
            <div className="week">
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="1"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="2"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="3"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="4"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="5"
                stateProp="enabled"
                type="today"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="6"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="7"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="8"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="9"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="10"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="11"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="12"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="13"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="14"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="15"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="16"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-instance"
                date="17"
                stateProp="enabled"
                type="selected"
              />
              <BuildingBlocks
                className="building-blocks-instance"
                date="18"
                stateProp="enabled"
                type="selected-middle"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="19"
                stateProp="enabled"
                type="selected-middle"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="20"
                stateProp="enabled"
                type="selected-middle"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="21"
                stateProp="enabled"
                type="selected-middle"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="22"
                extraRight={false}
                stateProp="enabled"
                type="selected-middle"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="23"
                stateProp="enabled"
                type="selected"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="24"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="25"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="26"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="27"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="28"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="29"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="30"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="31"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
            </div>
          </div>
          <div className="month">
            <div className="month-year-wrapper">
              <div className="month-year">September 2023</div>
            </div>
            <div className="week">
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="1"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="2"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="3"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="4"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="5"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="6"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="7"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="8"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="9"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="10"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="11"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="12"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="13"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="14"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="15"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="16"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="17"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="18"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="19"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="20"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="21"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="22"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="23"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="24"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="25"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="26"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="27"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="28"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="29"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="30"
                stateProp="enabled"
                type="default"
              />
            </div>
          </div>
          <div className="month">
            <div className="month-year-wrapper">
              <div className="month-year">October 2023</div>
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="1"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="2"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="3"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="4"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="5"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="6"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="7"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="8"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="9"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="10"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="11"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="12"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="13"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="14"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="15"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="16"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="17"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="18"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="19"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="20"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="21"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="22"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="23"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="24"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="25"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="26"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="27"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="28"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="29"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="30"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="31"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
            </div>
          </div>
          <div className="month">
            <div className="month-year-wrapper">
              <div className="month-year">November 2023</div>
            </div>
            <div className="week">
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="1"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="2"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="3"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="4"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="5"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="6"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="7"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="8"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="9"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="10"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="11"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="12"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="13"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="14"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="15"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="16"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="17"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="18"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="19"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="20"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="21"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="22"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="23"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="24"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="25"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="26"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="27"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="28"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="29"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="30"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
            </div>
          </div>
          <div className="month">
            <div className="month-year-wrapper">
              <div className="month-year">December 2023</div>
            </div>
            <div className="week">
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="1"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="2"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="3"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="4"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="5"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="6"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="7"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="8"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="9"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="10"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="11"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="12"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="13"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="14"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="15"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="16"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="17"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="18"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="19"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="20"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="21"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="22"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="23"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="24"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="25"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="26"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="27"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="28"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="29"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="30"
                stateProp="enabled"
                type="default"
              />
            </div>
            <div className="week">
              <BuildingBlocks
                className="building-blocks-local-m3-calendar-cell"
                date="31"
                stateProp="enabled"
                type="default"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
              <BuildingBlocks
                className="design-component-instance-node-2"
                stateProp="enabled"
                type="null"
              />
            </div>
          </div>
        </div>
      </div>
      <div className="local-actions">
        <div className="button-container">
          <Button
            className="design-component-instance-node-2"
            labelText="Cancel"
            showIcon={false}
            style="text"
          />
          <Button
            className="design-component-instance-node-2"
            labelText="OK"
            showIcon={false}
            style="text"
          />
        </div>
      </div>
    </div>
  );
};

ModalDatePicker.propTypes = {
  showClearButton: PropTypes.bool,
  headlineRange: PropTypes.string,
  supportingTextRange: PropTypes.string,
  supportingText: PropTypes.string,
  headline: PropTypes.string,
  type: PropTypes.oneOf(["full-screen-range"]),
};
